//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AltPowerPlan.Resources.Translation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AltPowerPlan.Resources.Translation.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A lightweight, modern Windows utility for effortless power plan management and switching..
        /// </summary>
        public static string AboutAppDescription {
            get {
                return ResourceManager.GetString("AboutAppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string AboutAuthor {
            get {
                return ResourceManager.GetString("AboutAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        public static string AboutCheckForUpdates {
            get {
                return ResourceManager.GetString("AboutCheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contribute on GitHub.
        /// </summary>
        public static string AboutCollaboratorsContributeButton {
            get {
                return ResourceManager.GetString("AboutCollaboratorsContributeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No additional contributors yet. Want to help? Submit a pull request!.
        /// </summary>
        public static string AboutCollaboratorsEmpty {
            get {
                return ResourceManager.GetString("AboutCollaboratorsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading contributors....
        /// </summary>
        public static string AboutCollaboratorsLoading {
            get {
                return ResourceManager.GetString("AboutCollaboratorsLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string AboutCollaboratorsRefresh {
            get {
                return ResourceManager.GetString("AboutCollaboratorsRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People who contributed code, design, or ideas to AltPowerPlan.
        /// </summary>
        public static string AboutCollaboratorsSubtitle {
            get {
                return ResourceManager.GetString("AboutCollaboratorsSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collaborators &amp; Contributors.
        /// </summary>
        public static string AboutCollaboratorsTitle {
            get {
                return ResourceManager.GetString("AboutCollaboratorsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} contributions.
        /// </summary>
        public static string AboutContributionsCount {
            get {
                return ResourceManager.GetString("AboutContributionsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string AboutLeadAuthor {
            get {
                return ResourceManager.GetString("AboutLeadAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issues.
        /// </summary>
        public static string AboutLinksIssues {
            get {
                return ResourceManager.GetString("AboutLinksIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository.
        /// </summary>
        public static string AboutLinksRepo {
            get {
                return ResourceManager.GetString("AboutLinksRepo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report a bug or suggestion.
        /// </summary>
        public static string AboutLinksReport {
            get {
                return ResourceManager.GetString("AboutLinksReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contributor.
        /// </summary>
        public static string AboutRoleContributor {
            get {
                return ResourceManager.GetString("AboutRoleContributor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update available.
        /// </summary>
        public static string AboutUpdateAvailable {
            get {
                return ResourceManager.GetString("AboutUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are up to date.
        /// </summary>
        public static string AboutUpToDate {
            get {
                return ResourceManager.GetString("AboutUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub Profile.
        /// </summary>
        public static string AboutViewProfile {
            get {
                return ResourceManager.GetString("AboutViewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        public static string DashboardActivateButton {
            get {
                return ResourceManager.GetString("DashboardActivateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Active Plan.
        /// </summary>
        public static string DashboardActivePlanHeader {
            get {
                return ResourceManager.GetString("DashboardActivePlanHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string DashboardActiveStatus {
            get {
                return ResourceManager.GetString("DashboardActiveStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Plan.
        /// </summary>
        public static string DashboardAddPlanButton {
            get {
                return ResourceManager.GetString("DashboardAddPlanButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Power Plans.
        /// </summary>
        public static string DashboardAvailablePlansHeader {
            get {
                return ResourceManager.GetString("DashboardAvailablePlansHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Scheme Template.
        /// </summary>
        public static string DashboardBaseTemplateLabel {
            get {
                return ResourceManager.GetString("DashboardBaseTemplateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string DashboardCancelButton {
            get {
                return ResourceManager.GetString("DashboardCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string DashboardCreateButton {
            get {
                return ResourceManager.GetString("DashboardCreateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Power Plan.
        /// </summary>
        public static string DashboardCreatePlanTitle {
            get {
                return ResourceManager.GetString("DashboardCreatePlanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows built-in power schemes have been restored..
        /// </summary>
        public static string DashboardDefaultsRestoredMessage {
            get {
                return ResourceManager.GetString("DashboardDefaultsRestoredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default schemes restored.
        /// </summary>
        public static string DashboardDefaultsRestoredTitle {
            get {
                return ResourceManager.GetString("DashboardDefaultsRestoredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete the active power plan. Please activate another plan first..
        /// </summary>
        public static string DashboardDeleteActivePlanError {
            get {
                return ResourceManager.GetString("DashboardDeleteActivePlanError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DashboardDeleteButton {
            get {
                return ResourceManager.GetString("DashboardDeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete the currently active plan.
        /// </summary>
        public static string DashboardDeleteDisabledTooltip {
            get {
                return ResourceManager.GetString("DashboardDeleteDisabledTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete &apos;{0}&apos;? This plan will be permanently removed..
        /// </summary>
        public static string DashboardDeletePlanMessage {
            get {
                return ResourceManager.GetString("DashboardDeletePlanMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Power Plan.
        /// </summary>
        public static string DashboardDeletePlanTitle {
            get {
                return ResourceManager.GetString("DashboardDeletePlanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t ask me again.
        /// </summary>
        public static string DashboardDoNotAskAgain {
            get {
                return ResourceManager.GetString("DashboardDoNotAskAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate.
        /// </summary>
        public static string DashboardDuplicateButton {
            get {
                return ResourceManager.GetString("DashboardDuplicateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string DashboardEditButton {
            get {
                return ResourceManager.GetString("DashboardEditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Power Plan.
        /// </summary>
        public static string DashboardEditPlanTitle {
            get {
                return ResourceManager.GetString("DashboardEditPlanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export (.pow).
        /// </summary>
        public static string DashboardExportButton {
            get {
                return ResourceManager.GetString("DashboardExportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Plan.
        /// </summary>
        public static string DashboardImportPlanButton {
            get {
                return ResourceManager.GetString("DashboardImportPlanButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit in Windows Settings.
        /// </summary>
        public static string DashboardOpenWindowsEdit {
            get {
                return ResourceManager.GetString("DashboardOpenWindowsEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power plan activated.
        /// </summary>
        public static string DashboardPlanActivated {
            get {
                return ResourceManager.GetString("DashboardPlanActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power plan created successfully.
        /// </summary>
        public static string DashboardPlanCreated {
            get {
                return ResourceManager.GetString("DashboardPlanCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create power plan.
        /// </summary>
        public static string DashboardPlanCreateFailed {
            get {
                return ResourceManager.GetString("DashboardPlanCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power plan deleted successfully.
        /// </summary>
        public static string DashboardPlanDeleted {
            get {
                return ResourceManager.GetString("DashboardPlanDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete power plan.
        /// </summary>
        public static string DashboardPlanDeleteFailed {
            get {
                return ResourceManager.GetString("DashboardPlanDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description (optional).
        /// </summary>
        public static string DashboardPlanDescriptionLabel {
            get {
                return ResourceManager.GetString("DashboardPlanDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter description....
        /// </summary>
        public static string DashboardPlanDescriptionPlaceholder {
            get {
                return ResourceManager.GetString("DashboardPlanDescriptionPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power plan duplicated.
        /// </summary>
        public static string DashboardPlanDuplicatedTitle {
            get {
                return ResourceManager.GetString("DashboardPlanDuplicatedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power plan exported.
        /// </summary>
        public static string DashboardPlanExportedTitle {
            get {
                return ResourceManager.GetString("DashboardPlanExportedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to export power plan.
        /// </summary>
        public static string DashboardPlanExportFailedTitle {
            get {
                return ResourceManager.GetString("DashboardPlanExportFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power plan imported.
        /// </summary>
        public static string DashboardPlanImportedTitle {
            get {
                return ResourceManager.GetString("DashboardPlanImportedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to import power plan.
        /// </summary>
        public static string DashboardPlanImportFailedTitle {
            get {
                return ResourceManager.GetString("DashboardPlanImportFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan Name.
        /// </summary>
        public static string DashboardPlanNameLabel {
            get {
                return ResourceManager.GetString("DashboardPlanNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter plan name....
        /// </summary>
        public static string DashboardPlanNamePlaceholder {
            get {
                return ResourceManager.GetString("DashboardPlanNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan name is required.
        /// </summary>
        public static string DashboardPlanNameRequired {
            get {
                return ResourceManager.GetString("DashboardPlanNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power plan updated successfully.
        /// </summary>
        public static string DashboardPlanUpdated {
            get {
                return ResourceManager.GetString("DashboardPlanUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update power plan.
        /// </summary>
        public static string DashboardPlanUpdateFailed {
            get {
                return ResourceManager.GetString("DashboardPlanUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balanced.
        /// </summary>
        public static string DashboardPresetBalanced {
            get {
                return ResourceManager.GetString("DashboardPresetBalanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically balances performance with energy consumption on capable hardware..
        /// </summary>
        public static string DashboardPresetBalancedDesc {
            get {
                return ResourceManager.GetString("DashboardPresetBalancedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Plan.
        /// </summary>
        public static string DashboardPresetCustom {
            get {
                return ResourceManager.GetString("DashboardPresetCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate from any existing power plan on your system..
        /// </summary>
        public static string DashboardPresetCustomDesc {
            get {
                return ResourceManager.GetString("DashboardPresetCustomDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a Preset or Custom Plan.
        /// </summary>
        public static string DashboardPresetHeader {
            get {
                return ResourceManager.GetString("DashboardPresetHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Performance.
        /// </summary>
        public static string DashboardPresetHigh {
            get {
                return ResourceManager.GetString("DashboardPresetHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favors performance, but may use more energy..
        /// </summary>
        public static string DashboardPresetHighDesc {
            get {
                return ResourceManager.GetString("DashboardPresetHighDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Saver.
        /// </summary>
        public static string DashboardPresetSaver {
            get {
                return ResourceManager.GetString("DashboardPresetSaver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saves energy by reducing computer performance where possible..
        /// </summary>
        public static string DashboardPresetSaverDesc {
            get {
                return ResourceManager.GetString("DashboardPresetSaverDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ultimate Performance.
        /// </summary>
        public static string DashboardPresetUltimate {
            get {
                return ResourceManager.GetString("DashboardPresetUltimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provides ultimate performance on higher-end PCs..
        /// </summary>
        public static string DashboardPresetUltimateDesc {
            get {
                return ResourceManager.GetString("DashboardPresetUltimateDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string DashboardRefreshButton {
            get {
                return ResourceManager.GetString("DashboardRefreshButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Defaults.
        /// </summary>
        public static string DashboardRestoreDefaultsButton {
            get {
                return ResourceManager.GetString("DashboardRestoreDefaultsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string DashboardSaveButton {
            get {
                return ResourceManager.GetString("DashboardSaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select and switch your active Windows power scheme.
        /// </summary>
        public static string DashboardSubtitle {
            get {
                return ResourceManager.GetString("DashboardSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Plans.
        /// </summary>
        public static string DashboardTitle {
            get {
                return ResourceManager.GetString("DashboardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Power Options.
        /// </summary>
        public static string DashboardWindowsOptionsButton {
            get {
                return ResourceManager.GetString("DashboardWindowsOptionsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Windows Control Panel Power Options.
        /// </summary>
        public static string DashboardWindowsOptionsTooltip {
            get {
                return ResourceManager.GetString("DashboardWindowsOptionsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string MenuHome {
            get {
                return ResourceManager.GetString("MenuHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MenuSettings {
            get {
                return ResourceManager.GetString("MenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Automation.
        /// </summary>
        public static string SettingsAutomationSection {
            get {
                return ResourceManager.GetString("SettingsAutomationSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically switch power plans when plugging in or running on battery.
        /// </summary>
        public static string SettingsAutoSwitchAcDcDescription {
            get {
                return ResourceManager.GetString("SettingsAutoSwitchAcDcDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-switch on AC / Battery.
        /// </summary>
        public static string SettingsAutoSwitchAcDcOption {
            get {
                return ResourceManager.GetString("SettingsAutoSwitchAcDcOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask for confirmation before deleting a power plan.
        /// </summary>
        public static string SettingsConfirmPlanDeletionDescription {
            get {
                return ResourceManager.GetString("SettingsConfirmPlanDeletionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Plan Deletion.
        /// </summary>
        public static string SettingsConfirmPlanDeletionOption {
            get {
                return ResourceManager.GetString("SettingsConfirmPlanDeletionOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt + Shift + P.
        /// </summary>
        public static string SettingsHotkeyAltShiftP {
            get {
                return ResourceManager.GetString("SettingsHotkeyAltShiftP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string SettingsHotkeyClear {
            get {
                return ResourceManager.GetString("SettingsHotkeyClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl + Alt + P.
        /// </summary>
        public static string SettingsHotkeyCtrlAltP {
            get {
                return ResourceManager.GetString("SettingsHotkeyCtrlAltP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl + Shift + P.
        /// </summary>
        public static string SettingsHotkeyCtrlShiftP {
            get {
                return ResourceManager.GetString("SettingsHotkeyCtrlShiftP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string SettingsHotkeyCustom {
            get {
                return ResourceManager.GetString("SettingsHotkeyCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press the shortcut anywhere to toggle the quick menu. Click the button to record any custom hotkey..
        /// </summary>
        public static string SettingsHotkeyDescription {
            get {
                return ResourceManager.GetString("SettingsHotkeyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This hotkey is already in use by another application or Windows..
        /// </summary>
        public static string SettingsHotkeyInUse {
            get {
                return ResourceManager.GetString("SettingsHotkeyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use at least one modifier key (Ctrl, Alt, Shift, Win) or a function key (F1-F24)..
        /// </summary>
        public static string SettingsHotkeyNeedModifier {
            get {
                return ResourceManager.GetString("SettingsHotkeyNeedModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string SettingsHotkeyNone {
            get {
                return ResourceManager.GetString("SettingsHotkeyNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Hotkey for Quick Menu.
        /// </summary>
        public static string SettingsHotkeyOption {
            get {
                return ResourceManager.GetString("SettingsHotkeyOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press keys....
        /// </summary>
        public static string SettingsHotkeyPressKeys {
            get {
                return ResourceManager.GetString("SettingsHotkeyPressKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string SettingsHotkeyReset {
            get {
                return ResourceManager.GetString("SettingsHotkeyReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win + Alt + P.
        /// </summary>
        public static string SettingsHotkeyWinAltP {
            get {
                return ResourceManager.GetString("SettingsHotkeyWinAltP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string SettingsLanguageOption {
            get {
                return ResourceManager.GetString("SettingsLanguageOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide window to system tray instead of taskbar when minimizing.
        /// </summary>
        public static string SettingsMinimizeToTrayDescription {
            get {
                return ResourceManager.GetString("SettingsMinimizeToTrayDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize to Tray.
        /// </summary>
        public static string SettingsMinimizeToTrayOption {
            get {
                return ResourceManager.GetString("SettingsMinimizeToTrayOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Plans.
        /// </summary>
        public static string SettingsPowerPlansSection {
            get {
                return ResourceManager.GetString("SettingsPowerPlansSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugged in (AC):.
        /// </summary>
        public static string SettingsPreferredAcPlanLabel {
            get {
                return ResourceManager.GetString("SettingsPreferredAcPlanLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On battery (DC):.
        /// </summary>
        public static string SettingsPreferredDcPlanLabel {
            get {
                return ResourceManager.GetString("SettingsPreferredDcPlanLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Menu Screen Position.
        /// </summary>
        public static string SettingsQuickMenuSideOption {
            get {
                return ResourceManager.GetString("SettingsQuickMenuSideOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Center.
        /// </summary>
        public static string SettingsScreenSideBottomCenter {
            get {
                return ResourceManager.GetString("SettingsScreenSideBottomCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Left.
        /// </summary>
        public static string SettingsScreenSideBottomLeft {
            get {
                return ResourceManager.GetString("SettingsScreenSideBottomLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Right (Taskbar Corner).
        /// </summary>
        public static string SettingsScreenSideBottomRight {
            get {
                return ResourceManager.GetString("SettingsScreenSideBottomRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Center.
        /// </summary>
        public static string SettingsScreenSideTopCenter {
            get {
                return ResourceManager.GetString("SettingsScreenSideTopCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Left.
        /// </summary>
        public static string SettingsScreenSideTopLeft {
            get {
                return ResourceManager.GetString("SettingsScreenSideTopLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Right.
        /// </summary>
        public static string SettingsScreenSideTopRight {
            get {
                return ResourceManager.GetString("SettingsScreenSideTopRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcuts.
        /// </summary>
        public static string SettingsShortcutsSection {
            get {
                return ResourceManager.GetString("SettingsShortcutsSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start silently minimized to system tray.
        /// </summary>
        public static string SettingsStartMinimizedDescription {
            get {
                return ResourceManager.GetString("SettingsStartMinimizedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Minimized.
        /// </summary>
        public static string SettingsStartMinimizedOption {
            get {
                return ResourceManager.GetString("SettingsStartMinimizedOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically launch AltPowerPlan on system startup.
        /// </summary>
        public static string SettingsStartWithWindowsDescription {
            get {
                return ResourceManager.GetString("SettingsStartWithWindowsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start with Windows.
        /// </summary>
        public static string SettingsStartWithWindowsOption {
            get {
                return ResourceManager.GetString("SettingsStartWithWindowsOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System &amp; Startup.
        /// </summary>
        public static string SettingsSystemSection {
            get {
                return ResourceManager.GetString("SettingsSystemSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string SettingsThemeDarkOption {
            get {
                return ResourceManager.GetString("SettingsThemeDarkOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string SettingsThemeLightOption {
            get {
                return ResourceManager.GetString("SettingsThemeLightOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string SettingsThemeOption {
            get {
                return ResourceManager.GetString("SettingsThemeOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string SettingsThemeSystemOption {
            get {
                return ResourceManager.GetString("SettingsThemeSystemOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active: {0}.
        /// </summary>
        public static string TrayActivePlanFormat {
            get {
                return ResourceManager.GetString("TrayActivePlanFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Plan.
        /// </summary>
        public static string TrayDeletePlanMenu {
            get {
                return ResourceManager.GetString("TrayDeletePlanMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string TrayExit {
            get {
                return ResourceManager.GetString("TrayExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active plan cannot be deleted.
        /// </summary>
        public static string TrayNoDeletablePlans {
            get {
                return ResourceManager.GetString("TrayNoDeletablePlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open AltPowerPlan.
        /// </summary>
        public static string TrayOpenWindow {
            get {
                return ResourceManager.GetString("TrayOpenWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Mode.
        /// </summary>
        public static string TrayQuickMenuTitle {
            get {
                return ResourceManager.GetString("TrayQuickMenuTitle", resourceCulture);
            }
        }
    }
}
